name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout myself
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt install python-pip libboost-dev libgoogle-glog-dev -y
        sudo -H python -m pip install --upgrade pip
        sudo -H python -m pip install cmake
    - name: Configure myself
      run: cmake -S . -B build
    - name: Cache llvm-src
      uses: actions/cache@v1
      with:
        path: build/_deps/llvm-src
        key: ${{ runner.os }}-llvm-src
    - name: Cache llvm-build
      uses: actions/cache@v1
      with:
        path: build/_deps/llvm-build
        key: ${{ runner.os }}-llvm-build
    - name: Cache llvm-subbuild
      uses: actions/cache@v1
      with:
        path: build/_deps/llvm-subbuild
        key: ${{ runner.os }}-llvm-subbuild
    - name: Build myself
      run: cmake --build build --target all
    - name: Test myself
      run: cmake --build build --target test
