name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
    - name: Checkout myself
      uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt install python3-pip libboost-coroutine-dev libgoogle-glog-dev -y
        sudo apt install libboost-stacktrace-dev -y || true
        sudo -H python3 -m pip install --upgrade pip
        sudo -H python3 -m pip install cmake
    - name: Configure myself
      run: cmake -S . -B build
    - name: Cache llvm-src
      uses: actions/cache@v1
      with:
        path: build/_deps/llvm-src
        key: ${{ matrix.os }}-llvm-src
    - name: Cache llvm-build
      uses: actions/cache@v1
      with:
        path: build/_deps/llvm-build
        key: ${{ matrix.os }}-llvm-build
    - name: Cache llvm-subbuild
      uses: actions/cache@v1
      with:
        path: build/_deps/llvm-subbuild
        key: ${{ matrix.os }}-llvm-subbuild
    - name: Build myself
      run: cmake --build build --target all
    - name: Test myself
      run: cmake --build build --target test
